// @generated by @hexagen/sync
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import deterministicCore from '../../eslint.deterministic-core.js';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  // Deterministic core: no ambient randomness or wall clock in src/domain/**.
  ...deterministicCore(),
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
);
