import { describe, test, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CanvasFfmpegVideoCompositor } from "../CanvasFfmpegVideoCompositor.js";
import { canonicalMp4Request } from "./canonical-mp4-request.js";
import {
  compositorGoldenKey,
  goldenPlatformKeys,
  goldenRun,
  isRecordingGoldens,
  missingGoldenMapMessage,
  recordGoldenMap,
  resolveGoldenMap,
  type GoldenFixture,
  type GoldenMap,
  type GoldenRun,
} from "./compositor-golden-key.js";

/**
 * VE3b1 — the audio byte golden.
 *
 * A SEPARATE fixture file (`compositor-goldens-mp4-audio.json`) and a
 * SEPARATE test file from `CanvasFfmpegVideoCompositor.byte-golden.test.ts`.
 * `recordGoldenMap` (via `mergeGoldenFixture`) replaces the *entire* map
 * under a platform key, so recording this golden must never run the silent
 * suite's own record path — that would re-record the silent cell (identical
 * bytes or not, the rule this repo holds to is about the *process*, not the
 * outcome: "never re-record an existing golden"). Keeping the two suites (and
 * fixtures) apart makes that true by construction: `RECORD_COMPOSITOR_GOLDENS=1`
 * scoped to this file's own vitest invocation cannot touch the other file.
 *
 * The input bed is generated deterministically inside the test by the pinned
 * ffmpeg-static binary itself (`-f lavfi sine=...`, fixed sample rate and
 * duration, PCM so there is no double-encode) — no audio fixture is
 * committed, matching the brief.
 *
 * Fields mirror VG2's shape: `fileHash` (the whole muxed file — container
 * framing, both streams), `audioStreamHash` (the extracted AAC elementary
 * stream via `-map 0:a -c copy -f adts`, no re-encode — proves the encoder's
 * own bytes, the way `streamHash` in the silent golden proves libx264's), and
 * the same version/thread provenance fields as VG2 so a mismatch here reads
 * as a version change first.
 */

const AUDIO_GOLDEN_FIELD_COUNT = 5;
const CANONICAL_BED_DURATION_SEC = 3; // longer than canonicalMp4Request()'s durationSec=2, so the cut path is exercised.

const sha256 = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");

const require = createRequire(import.meta.url);
const ffmpegStatic = require("ffmpeg-static") as string | null;
const ffmpegOverride = process.env.COMPOSITOR_FFMPEG_PATH;
const ffmpegPath =
  ffmpegOverride !== undefined
    ? ffmpegOverride === ""
      ? null
      : ffmpegOverride
    : typeof ffmpegStatic === "string"
      ? ffmpegStatic
      : null;
const ffmpegProbe = ffmpegPath
  ? spawnSync(ffmpegPath, ["-version"], { encoding: "utf8", timeout: 5_000 })
  : undefined;
const ffmpegOk = ffmpegProbe?.status === 0;
const skipReason = ffmpegOk
  ? undefined
  : `ffmpeg-static binary cannot execute${ffmpegProbe?.error ? ` (${ffmpegProbe.error.message})` : ffmpegProbe ? ` (exited ${ffmpegProbe.status})` : " (path is null)"}`;

function parseFfmpegVersion(versionStdout: string): string {
  const match = /ffmpeg version (\S+)/.exec(versionStdout);
  if (!match)
    throw new Error(`could not parse ffmpeg version from: ${versionStdout.slice(0, 200)}`);
  return match[1];
}

function parseX264Banner(video: Uint8Array): {
  readonly version: string;
  readonly threads: string;
} {
  const text = Buffer.from(video).toString("latin1");
  const match = /x264 - (core \d+ \S+ \S+) - .*?threads=(\d+)/.exec(text);
  if (!match)
    throw new Error("no x264 SEI banner found in the encoded MP4 (was -fflags +bitexact changed?)");
  return { version: match[1], threads: match[2] };
}

/** The music bed: a deterministic sine wave, generated by the pinned binary. */
function generateSineBedWav(ffmpeg: string, durationSec: number, sampleRate: number): Uint8Array {
  const dir = mkdtempSync(join(tmpdir(), "cf-audio-golden-bed-"));
  try {
    const outPath = join(dir, "bed.wav");
    const result = spawnSync(
      ffmpeg,
      [
        "-y",
        "-f",
        "lavfi",
        "-i",
        `sine=frequency=440:sample_rate=${sampleRate}:duration=${durationSec}`,
        "-c:a",
        "pcm_s16le",
        "-f",
        "wav",
        outPath,
      ],
      { timeout: 10_000 },
    );
    if (result.status !== 0) {
      throw new Error(
        `sine bed generation failed (exit ${String(result.status)}): ${result.stderr?.toString()}`,
      );
    }
    return new Uint8Array(readFileSync(outPath));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Extract the AAC elementary stream (ADTS framing synthesized from the mp4 esds), no re-encode. */
function extractAudioStream(ffmpeg: string, mp4Path: string, outPath: string): Uint8Array {
  const result = spawnSync(
    ffmpeg,
    ["-y", "-i", mp4Path, "-map", "0:a", "-c", "copy", "-f", "adts", outPath],
    {
      timeout: 30_000,
    },
  );
  if (result.status !== 0) {
    throw new Error(
      `audio stream extraction failed (exit ${String(result.status)}): ${result.stderr?.toString().slice(-2000)}`,
    );
  }
  return readFileSync(outPath);
}

const fixturesDir =
  process.env.COMPOSITOR_GOLDEN_FIXTURE_DIR ??
  join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const goldensPath = join(fixturesDir, "compositor-goldens-mp4-audio.json");
const fixture = JSON.parse(readFileSync(goldensPath, "utf8")) as GoldenFixture;

const finishGolden = (key: string, observed: GoldenMap, run: GoldenRun): void => {
  if (run.kind === "record") {
    recordGoldenMap(goldensPath, key, observed, AUDIO_GOLDEN_FIELD_COUNT);
    return;
  }
  expect(observed).toEqual(run.map);
};

describe("CanvasFfmpegVideoCompositor audio byte golden (VE3b1)", () => {
  const key = compositorGoldenKey();
  const recording = isRecordingGoldens();
  const goldens = resolveGoldenMap(fixture, key);
  const missingMessage = missingGoldenMapMessage(key, goldenPlatformKeys(fixture), {
    fixtureFile: "compositor-goldens-mp4-audio.json",
    cellsHint:
      "5 fields (fileHash, audioStreamHash, ffmpegVersion, x264Version, threads) for the one canonical timeline + bed",
  });

  test.runIf(process.env.CI)("the ffmpeg-static binary executes on CI", () => {
    expect(ffmpegOk, skipReason).toBe(true);
  });

  test.skipIf(!recording && !ffmpegOk)(
    (!recording ? skipReason : undefined) ??
      "the canonical timeline with a music bed matches the committed audio byte golden for this platform",
    { timeout: 60_000 },
    async () => {
      if (!ffmpegOk) throw new Error(skipReason);
      if (!ffmpegPath) throw new Error("ffmpeg-static binary is not available");
      const run = goldenRun(goldens, recording, missingMessage);

      const request = canonicalMp4Request();
      const audio = generateSineBedWav(ffmpegPath, CANONICAL_BED_DURATION_SEC, 48_000);
      // Same binary that encodes must be the same binary this file probes and
      // extracts streams with (`ffmpegPath`, honouring COMPOSITOR_FFMPEG_PATH) —
      // otherwise a hash mismatch could mean "two different ffmpeg builds",
      // not "the encoder changed".
      const { video } = await new CanvasFfmpegVideoCompositor({ ffmpegPath }).compositeVideo({
        ...request,
        audio,
      });
      const banner = parseX264Banner(video);

      const dir = mkdtempSync(join(tmpdir(), "cf-audio-golden-"));
      try {
        const mp4Path = join(dir, "canonical.mp4");
        writeFileSync(mp4Path, Buffer.from(video));
        const audioStream = extractAudioStream(ffmpegPath, mp4Path, join(dir, "canonical.aac"));

        const observed: GoldenMap = {
          fileHash: sha256(video),
          audioStreamHash: sha256(audioStream),
          ffmpegVersion: parseFfmpegVersion(ffmpegProbe?.stdout ?? ""),
          x264Version: banner.version,
          threads: banner.threads,
        };

        finishGolden(key, observed, run);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    },
  );
});
