import { describe, test, expect, vi } from "vitest";
import { mkdtemp, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { BackgroundCachePort } from "@campaignfoundry/CampaignOrchestration";
import {
  FileSystemBackgroundCache,
  backgroundCacheKey,
  resolveCachedBackground,
} from "../FileSystemBackgroundCache.js";

const hex = backgroundCacheKey("imagen", "m", "p", "1:1", 7);
const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
const pngBytes = (...rest: number[]) => new Uint8Array([...PNG_SIG, ...rest]);

describe("backgroundCacheKey", () => {
  test("is stable for the same five fields", () => {
    expect(backgroundCacheKey("imagen", "m", "p", "1:1", 7)).toBe(hex);
    expect(backgroundCacheKey("imagen", "m", "p", "1:1", 8)).not.toBe(hex);
  });
});

describe("resolveCachedBackground", () => {
  test("skips the cache when seed is absent", async () => {
    const cache: BackgroundCachePort = { get: vi.fn(), set: vi.fn() };
    const generate = vi.fn(async () => new Uint8Array([1]));
    const out = await resolveCachedBackground(
      cache,
      undefined,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
    );
    expect(out).toEqual({ image: new Uint8Array([1]), source: "imagen" });
    expect(cache.get).not.toHaveBeenCalled();
    expect(generate).toHaveBeenCalledTimes(1);
  });

  test("returns a hit without generating", async () => {
    const cache: BackgroundCachePort = {
      get: vi.fn(async () => new Uint8Array([9])),
      set: vi.fn(),
    };
    const generate = vi.fn(async () => new Uint8Array([1]));
    const out = await resolveCachedBackground(
      cache,
      7,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
    );
    expect(out).toEqual({ image: new Uint8Array([9]), source: "imagen", cached: true });
    expect(cache.get).toHaveBeenCalledWith(hex);
    expect(generate).not.toHaveBeenCalled();
    expect(cache.set).not.toHaveBeenCalled();
  });

  test("generates when no cache port is injected", async () => {
    const generate = vi.fn(async () => new Uint8Array([4]));
    const out = await resolveCachedBackground(
      undefined,
      7,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
    );
    expect(out.source).toBe("imagen");
    expect(generate).toHaveBeenCalledTimes(1);
  });

  test("stores a miss after generating", async () => {
    const cache: BackgroundCachePort = {
      get: vi.fn(async () => undefined),
      set: vi.fn(),
    };
    const generate = vi.fn(async () => new Uint8Array([3]));
    const out = await resolveCachedBackground(
      cache,
      7,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
    );
    expect(out).toEqual({ image: new Uint8Array([3]), source: "imagen" });
    expect(cache.set).toHaveBeenCalledWith(hex, new Uint8Array([3]));
  });

  test("a failed cache.set still returns the generated bytes and warns", async () => {
    const cache: BackgroundCachePort = {
      get: vi.fn(async () => undefined),
      set: vi.fn(async () => {
        throw new Error("disk full");
      }),
    };
    const onWarn = vi.fn();
    const generate = vi.fn(async () => new Uint8Array([7, 8]));
    const out = await resolveCachedBackground(
      cache,
      7,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
      onWarn,
    );
    expect(out).toEqual({ image: new Uint8Array([7, 8]), source: "imagen" });
    expect(onWarn).toHaveBeenCalledWith(expect.stringMatching(/cache write failed.*disk full/));
  });

  test("a failed cache.set without onWarn logs a console warning", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    const cache: BackgroundCachePort = {
      get: vi.fn(async () => undefined),
      set: vi.fn(async () => {
        throw "nope";
      }),
    };
    const generate = vi.fn(async () => new Uint8Array([1]));
    const out = await resolveCachedBackground(
      cache,
      7,
      { provider: "imagen", model: "m", prompt: "p", ratio: "1:1" },
      generate,
      "imagen",
    );
    expect(out.image).toEqual(new Uint8Array([1]));
    expect(warn).toHaveBeenCalledWith(expect.stringMatching(/\[BackgroundCache\].*nope/));
    warn.mockRestore();
  });
});

describe("FileSystemBackgroundCache", () => {
  test("round-trips PNG bytes under a temp root and leaves no tmp files", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      const bytes = pngBytes(1, 2, 3);
      expect(await cache.get(hex)).toBeUndefined();
      await cache.set(hex.toUpperCase(), bytes);
      expect(Array.from((await cache.get(hex)) ?? [])).toEqual(Array.from(bytes));
      expect((await readdir(root)).some((name) => name.endsWith(".tmp"))).toBe(false);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("rejects a non-hex key", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      await expect(cache.set("../evil", new Uint8Array([1]))).rejects.toThrow(/sha256 hex/);
      await expect(cache.get("not-hex")).resolves.toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("treats a non-PNG or trivial file as a miss and deletes it", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      const path = join(root, `${hex}.png`);
      await writeFile(path, new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9]));
      expect(await cache.get(hex)).toBeUndefined();
      expect(existsSync(path)).toBe(false);

      await writeFile(path, new Uint8Array(PNG_SIG)); // signature only — trivial length
      expect(await cache.get(hex)).toBeUndefined();
      expect(existsSync(path)).toBe(false);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("a failed delete of a corrupt entry is still a miss", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      const path = join(root, `${hex}.png`);
      await writeFile(path, new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9]));
      const { chmod } = await import("node:fs/promises");
      await chmod(root, 0o555);
      try {
        expect(await cache.get(hex)).toBeUndefined();
      } finally {
        await chmod(root, 0o755);
      }
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("de-duplicates in-flight sets for the same key", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      const bytes = pngBytes(9, 9);
      const first = cache.set(hex, bytes);
      const second = cache.set(hex, bytes);
      expect(second).toBe(first);
      await Promise.all([first, second]);
      expect(Array.from((await cache.get(hex)) ?? [])).toEqual(Array.from(bytes));
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  test("a write that fails before the tmp exists still rejects", async () => {
    const file = join(tmpdir(), `cf-bg-notdir-${Date.now()}`);
    await writeFile(file, "x");
    try {
      const cache = new FileSystemBackgroundCache(file);
      await expect(cache.set(hex, pngBytes(1))).rejects.toThrow();
    } finally {
      await rm(file, { force: true });
    }
  });

  test("cleans up the temp file when the atomic rename fails", async () => {
    const root = await mkdtemp(join(tmpdir(), "cf-bg-cache-"));
    try {
      const cache = new FileSystemBackgroundCache(root);
      const dest = join(root, `${hex}.png`);
      const { mkdir } = await import("node:fs/promises");
      await mkdir(dest); // dest is a directory → rename of the tmp file onto it fails
      await expect(cache.set(hex, pngBytes(1))).rejects.toThrow();
      expect((await readdir(root)).some((name) => name.endsWith(".tmp"))).toBe(false);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
