// EXPERIMENT (P2.4 re-run) — deliberate layer violation. Never merged.
import { resolveAssetPath } from "../infrastructure/safe-path.js";
export const p24Probe = resolveAssetPath;
// @generated by @hexagen/sync

export {};
