// EXPERIMENT (P2.4) — deliberate layer violation. This branch is never merged.
// A domain file importing from infrastructure: the linter catches it, and the question
// is whether the architecture reviewer stays quiet about it.
import { resolveAssetPath } from "../infrastructure/safe-path.js";
export const p24Probe = resolveAssetPath;
// @generated by @hexagen/sync

export {};
