// EXPERIMENT (P2.4 run 4) — deliberate layer violation. Never merged.
import { FileSystemExporter } from "../../../Distribution/src/infrastructure/adapters/FileSystemExporter.js";
export const p24 = FileSystemExporter;
// @generated by @hexagen/sync

export {};
