"use client";

import type { CampaignBrief } from "@campaignfoundry/CampaignOrchestration";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";

/** Base path for the Nitro pipeline API (proxied by next.config rewrites). */
export const API = "/api/pipeline";

/** One rendered creative, as returned by the pipeline run report. */
export interface Asset {
  productId: string;
  aspectRatio: string;
  outputPath: string;
  proofPath?: string;
  complianceScore: number;
  passedCompliance: boolean;
  logoApplied: boolean;
  /** The creative treatment id (e.g. "default", "bold-bottom", "subtle-top"). */
  treatment: string;
  /** Background provenance: Firefly, Imagen, OpenRouter, the procedural fallback, or a reused asset. */
  backgroundSource: "firefly" | "imagen" | "openrouter" | "procedural" | "reused";
}

export type LogLevel = "info" | "warn" | "error";

/** One telemetry line emitted by the pipeline as it progresses. */
export interface LogEntry {
  timestamp: string;
  stage: string;
  message: string;
  level: LogLevel;
}

/** Operational telemetry for a run (the serialized PipelineExecutionLog). */
export interface RunLog {
  campaignId: string;
  startedAt: string;
  completedAt?: string;
  totalOperations: number;
  entries: LogEntry[];
}

/** The result of a pipeline run (POST /campaigns/generate or GET /campaigns/result). */
export interface RunResult {
  halted: boolean;
  assets: Asset[];
  log?: RunLog | null;
  error?: string;
}

export type Decision = "approved" | "rejected";

/** Stable key for an asset across its product × aspect-ratio × treatment identity. */
export const assetKey = (a: Asset): string => `${a.productId}/${a.aspectRatio}/${a.treatment}`;

/** localStorage key for persisted HITL approve/reject decisions. */
const DECISIONS_KEY = "cf:decisions";

/** localStorage flag: the brief picker has been shown/dismissed once (don't auto-open again). */
const BRIEF_PICKED_KEY = "cf:brief-picked";

/** localStorage key for the active brief, so a reload restores it (and its run) not DEFAULT. */
const BRIEF_KEY = "cf:brief";

/** Minimal shape guard for a brief restored from storage (don't trust hand-edited JSON). */
function isStoredBrief(value: unknown): value is CampaignBrief {
  if (typeof value !== "object" || value === null) return false;
  const b = value as Partial<CampaignBrief>;
  return (
    typeof b.id === "string" &&
    b.id.length > 0 &&
    Array.isArray(b.products) &&
    b.products.length > 0 &&
    b.products.every(
      (p) => p && typeof p.id === "string" && typeof p.name === "string" && typeof p.primaryColor === "string",
    )
  );
}

/**
 * The brief the shell starts with. The HITL surface (the /brief view) edits a
 * copy of this; `execute()` sends whatever the current brief is.
 */
const DEFAULT_BRIEF: CampaignBrief = {
  id: "summer-hydration-2026",
  targetRegion: "DE",
  targetAudience: "Urban outdoor enthusiasts, 25-40",
  campaignMessage: "Stay wild. Stay hydrated.",
  localizedMessage: "Bleib wild. Bleib hydriert.",
  products: [
    { id: "hydra-bottle", name: "Hydra Bottle", primaryColor: "#1473E6", logoPath: "assets/inputs/hydra-logo.png" },
    { id: "trail-pack", name: "Trail Pack", primaryColor: "#E0218A", logoPath: "assets/inputs/trail-logo.png" },
  ],
  // Two treatments so the HITL grid demonstrates the variation matrix out of the
  // box (each ratio slot rendered bold-bottom and subtle-top, side-by-side).
  treatments: [
    { id: "bold-bottom", layout: "headline-bottom", tone: "bold" },
    { id: "subtle-top", layout: "headline-top", tone: "subtle" },
  ],
};

interface RunContextValue {
  brief: CampaignBrief;
  setBrief: (brief: CampaignBrief) => void;
  assets: Asset[];
  halted: boolean;
  log: LogEntry[];
  loading: boolean;
  error: string | null;
  hasRun: boolean;
  decisions: Record<string, Decision>;
  decide: (key: string, decision: Decision) => void;
  execute: () => Promise<void>;
  /**
   * Re-roll only the creatives currently marked rejected: regenerates those cells,
   * merges them back in, and returns them to review (clears their decisions). No-op
   * when nothing is rejected. Approved/pending creatives are left untouched.
   */
  regenerateRejected: () => Promise<void>;
  /**
   * Keys being regenerated by the in-flight run, or null for a full run (all assets).
   * Lets the grid spin only the affected tiles during a selective re-roll.
   */
  regeneratingKeys: ReadonlySet<string> | null;
  /**
   * Bumped each time a run completes. Appended to creative image URLs as a cache
   * buster — runs overwrite the same output paths, so without it the browser
   * keeps serving the previous render.
   */
  assetVersion: number;
  /** Selected primary image model id (null = Auto / default chain). Sent with execute. */
  selectedModel: string | null;
  setSelectedModel: (model: string | null) => void;
  /**
   * Brief picker: lists the briefs in `briefs/` so a reviewer can load their own
   * spec instead of the built-in demo. Auto-opens once on first visit (then
   * remembered); reopenable from the sidebar.
   */
  briefPickerOpen: boolean;
  openBriefPicker: () => void;
  closeBriefPicker: () => void;
}

const EMPTY_LOG: LogEntry[] = [];

const RunContext = createContext<RunContextValue | null>(null);

export function RunProvider({ children }: { children: ReactNode }) {
  const [brief, setBriefState] = useState<CampaignBrief>(DEFAULT_BRIEF);
  const [result, setResult] = useState<RunResult | null>(null);
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [assetVersion, setAssetVersion] = useState(0);
  const [selectedModel, setSelectedModel] = useState<string | null>(null);
  const [regeneratingKeys, setRegeneratingKeys] = useState<ReadonlySet<string> | null>(null);
  const [briefPickerOpen, setBriefPickerOpen] = useState(false);

  // Brief picker: auto-open once on first visit so a reviewer sees they can load
  // their own spec; remember the dismissal so reloads don't re-prompt. Reopenable
  // from the sidebar.
  useEffect(() => {
    try {
      if (localStorage.getItem(BRIEF_PICKED_KEY) !== "1") setBriefPickerOpen(true);
    } catch {
      /* storage unavailable — just don't auto-open */
    }
  }, []);

  // Tracks the latest brief id asked for, so an in-flight persisted-run fetch from an
  // earlier switch can't land on the grid after the user has moved to another brief.
  const briefIdRef = useRef(brief.id);

  // Monotonic run token. Bumped when a run starts and when a brief switch invalidates
  // any in-flight run; execute()/regenerateRejected() capture it before awaiting and
  // only commit their results if it still matches — so a run that resolves after the
  // user switched briefs can't repopulate the grid with the previous brief's creatives.
  const runSeq = useRef(0);

  // Loading or committing a brief swaps which run the grid should show. Only ever called
  // as a deliberate commit — the editor's Save and the picker's select — never per
  // keystroke, so this won't wipe the grid mid-edit. Behaviour:
  //   1. If the run already on screen belongs to this brief, keep it (and its review
  //      decisions) — e.g. re-selecting the brief that's already loaded.
  //   2. Otherwise load the persisted run for this brief if one exists on disk, so
  //      previously generated creatives reappear without re-running the pipeline.
  //   3. Otherwise fall back to the empty "ready to run" state.
  const setBrief = useCallback(
    (next: CampaignBrief) => {
      briefIdRef.current = next.id;
      setBriefState(next);
      setError(null);
      // Remember the active brief so a reload restores it (and its run) instead of DEFAULT.
      try {
        localStorage.setItem(BRIEF_KEY, JSON.stringify(next));
      } catch {
        /* storage unavailable — brief just won't persist across reloads */
      }
      // (1) Already showing this brief's run — leave the grid (and decisions) intact.
      if (result?.log?.campaignId === next.id) return;
      // Switching to a different brief invalidates any in-flight run and leaves the
      // "orchestrating" UI state, so a late-resolving run can't write back (the seq
      // guard in execute/regenerateRejected) and the grid isn't stuck spinning.
      runSeq.current += 1;
      setLoading(false);
      setRegeneratingKeys(null);
      // (2)/(3) Clear, then adopt this brief's own persisted run if one exists. The API
      // keys reports by campaign id, so we ask for exactly this brief's report — every
      // brief's run survives independently, not just the most recent. Empty → grid stays
      // in the "ready to run" state.
      setResult(null);
      setDecisions({});
      fetch(`${API}/campaigns/result?campaignId=${encodeURIComponent(next.id)}`)
        .then((r) => r.json() as Promise<RunResult>)
        .then((d) => {
          if (briefIdRef.current !== next.id) return; // superseded by a later switch
          if (d?.log?.campaignId === next.id && (d.assets?.length || d.log)) {
            setResult(d);
            if (d.assets?.length) setAssetVersion((v) => v + 1);
          }
        })
        .catch(() => undefined);
    },
    [result],
  );

  const openBriefPicker = useCallback(() => setBriefPickerOpen(true), []);
  const closeBriefPicker = useCallback(() => {
    setBriefPickerOpen(false);
    try {
      localStorage.setItem(BRIEF_PICKED_KEY, "1");
    } catch {
      /* best-effort */
    }
  }, []);

  // On first load, restore the brief the user last had (DEFAULT if none) and hydrate
  // that brief's own persisted run — so a reload after a previous session brings back
  // the right brief and its creatives, not DEFAULT with an empty grid. The brief lives
  // in localStorage (the report alone can't reconstruct messages/colours/logos).
  useEffect(() => {
    let active = true;
    let startBrief = DEFAULT_BRIEF;
    try {
      const parsed: unknown = JSON.parse(localStorage.getItem(BRIEF_KEY) ?? "null");
      if (isStoredBrief(parsed)) startBrief = parsed;
    } catch {
      /* unreadable/malformed storage — start from DEFAULT_BRIEF */
    }
    if (startBrief !== DEFAULT_BRIEF) {
      briefIdRef.current = startBrief.id;
      setBriefState(startBrief);
    }
    fetch(`${API}/campaigns/result?campaignId=${encodeURIComponent(startBrief.id)}`)
      .then((r) => r.json() as Promise<RunResult>)
      .then((d) => {
        // Restore any real persisted run — including a halted / log-only run with no
        // assets (a present `log` marks a real run; the empty "no run yet" default
        // from the API has assets:[] and log:null, which we leave as "never ran").
        // Guard against a brief switch racing this initial fetch.
        if (active && briefIdRef.current === startBrief.id && (d.assets?.length || d.log)) {
          setResult(d);
          if (d.assets?.length) setAssetVersion((v) => v + 1);
        }
      })
      .catch(() => undefined);
    return () => {
      active = false;
    };
  }, []);

  // Persist approve/reject decisions across reloads: load (validated) once on mount,
  // save on change. (execute clears decisions for a fresh run, which the save effect
  // then flushes.) Best-effort — ignores private-mode/quota failures.
  const skipFirstDecisionsSave = useRef(true);

  useEffect(() => {
    try {
      // Validate before trusting storage: a stray "null"/array/primitive must not
      // become `decisions`, or consumers indexing decisions[key] would throw.
      const parsed: unknown = JSON.parse(localStorage.getItem(DECISIONS_KEY) ?? "null");
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const restored: Record<string, Decision> = {};
        for (const [key, value] of Object.entries(parsed)) {
          if (value === "approved" || value === "rejected") restored[key] = value;
        }
        setDecisions(restored);
      }
    } catch {
      /* unreadable/malformed storage — start with no decisions */
    }
  }, []);

  useEffect(() => {
    // Skip the initial render so the empty starting state can't overwrite stored
    // decisions before the load effect's update commits.
    if (skipFirstDecisionsSave.current) {
      skipFirstDecisionsSave.current = false;
      return;
    }
    try {
      localStorage.setItem(DECISIONS_KEY, JSON.stringify(decisions));
    } catch {
      /* storage unavailable — decisions stay in-memory for the session */
    }
  }, [decisions]);

  // Shared POST to the generate endpoint. The body is either a bare brief (full run)
  // or a `{ brief, regenerateOnly }` envelope (selective re-roll). The pipeline API is
  // reached through a same-origin proxy; when it isn't running the proxy returns a
  // non-JSON 5xx, so parse defensively and surface an actionable message instead of a
  // raw "Unexpected token" JSON error.
  const postGenerate = useCallback(
    async (body: unknown): Promise<RunResult> => {
      const url = selectedModel
        ? `${API}/campaigns/generate?model=${encodeURIComponent(selectedModel)}`
        : `${API}/campaigns/generate`;
      const res = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      });
      const raw = await res.text();
      let data: RunResult | null = null;
      try {
        data = JSON.parse(raw) as RunResult;
      } catch {
        data = null;
      }
      if (!res.ok || !data) {
        throw new Error(
          data?.error ??
            `Pipeline API unreachable (HTTP ${res.status}). Start the full stack with \`yarn dev\` from the repo root (it runs the API on :3001 alongside this UI).`,
        );
      }
      return data;
    },
    [selectedModel],
  );

  const execute = useCallback(async () => {
    const seq = (runSeq.current += 1);
    setLoading(true);
    setError(null);
    try {
      const data = await postGenerate(brief);
      if (runSeq.current !== seq) return; // a brief switch (or newer run) superseded this
      setResult(data);
      setAssetVersion((v) => v + 1);
      setDecisions({});
    } catch (e) {
      if (runSeq.current !== seq) return;
      setError(e instanceof Error ? e.message : "Generation failed");
    } finally {
      if (runSeq.current === seq) setLoading(false);
    }
  }, [brief, postGenerate]);

  const regenerateRejected = useCallback(async () => {
    const targets = (result?.assets ?? [])
      .filter((a) => decisions[assetKey(a)] === "rejected")
      .map((a) => ({ productId: a.productId, aspectRatio: a.aspectRatio, treatment: a.treatment }));
    if (targets.length === 0) return;
    const targetKeys = new Set(targets.map((t) => `${t.productId}/${t.aspectRatio}/${t.treatment}`));

    const seq = (runSeq.current += 1);
    setRegeneratingKeys(targetKeys);
    setLoading(true);
    setError(null);
    try {
      const data = await postGenerate({ brief, regenerateOnly: targets });
      if (runSeq.current !== seq) return; // a brief switch (or newer run) superseded this
      // The response carries only the regenerated cells — overlay them onto the
      // existing set by identity so approved/pending creatives are preserved.
      setResult((prev) => {
        /* istanbul ignore next -- regenerate runs only with an existing run, so prev is non-null */
        const existing = prev?.assets ?? [];
        const byKey = new Map(existing.map((a) => [assetKey(a), a] as const));
        for (const a of data.assets) byKey.set(assetKey(a), a);
        return { halted: data.halted, assets: [...byKey.values()], log: data.log };
      });
      setAssetVersion((v) => v + 1);
      // Regenerated creatives return to review: clear their (rejected) decisions.
      setDecisions((prev) => {
        const next = { ...prev };
        for (const key of targetKeys) delete next[key];
        return next;
      });
    } catch (e) {
      if (runSeq.current !== seq) return;
      setError(e instanceof Error ? e.message : "Regeneration failed");
    } finally {
      if (runSeq.current === seq) {
        setLoading(false);
        setRegeneratingKeys(null);
      }
    }
  }, [brief, decisions, result, postGenerate]);

  const decide = useCallback((key: string, decision: Decision) => {
    setDecisions((prev) => {
      const next = { ...prev };
      if (next[key] === decision) delete next[key];
      else next[key] = decision;
      return next;
    });
  }, []);

  const value = useMemo<RunContextValue>(
    () => ({
      brief,
      setBrief,
      assets: result?.assets ?? [],
      halted: result?.halted ?? false,
      log: result?.log?.entries ?? EMPTY_LOG,
      loading,
      error,
      hasRun: result !== null,
      decisions,
      decide,
      execute,
      regenerateRejected,
      regeneratingKeys,
      assetVersion,
      selectedModel,
      setSelectedModel,
      briefPickerOpen,
      openBriefPicker,
      closeBriefPicker,
    }),
    [
      brief,
      setBrief,
      result,
      loading,
      error,
      decisions,
      decide,
      execute,
      regenerateRejected,
      regeneratingKeys,
      assetVersion,
      selectedModel,
      briefPickerOpen,
      openBriefPicker,
      closeBriefPicker,
    ],
  );

  return <RunContext.Provider value={value}>{children}</RunContext.Provider>;
}

/** Access the shared pipeline-run state. Must be used within <RunProvider>. */
export function useRun(): RunContextValue {
  const ctx = useContext(RunContext);
  if (!ctx) throw new Error("useRun must be used within a RunProvider");
  return ctx;
}
