/**
 * Where a creative's background came from:
 * - `imagen`     — generated by Google Imagen
 * - `openrouter` — generated via OpenRouter (e.g. Grok Imagine), the second GenAI
 *                  source used when Imagen is unavailable / rate-limited
 * - `procedural` — the offline gradient (the GenAI-free default, or the last-resort
 *                  fallback when every GenAI provider is unavailable)
 * - `reused`     — a brief-supplied input asset, reused as-is
 *
 * Surfaced on the asset and in the run log so the GenAI fallback chain is visible
 * (the pipeline degrades rather than failing a campaign).
 */
export type BackgroundSource = "imagen" | "openrouter" | "procedural" | "reused";
