/**
 * Where a creative's background came from:
 * - `firefly`    — generated by Adobe Firefly Services (v3)
 * - `imagen`     — generated by Google Imagen
 * - `openrouter` — generated via OpenRouter (e.g. Grok Imagine), used when the
 *                  primary GenAI source is unavailable / rate-limited
 * - `procedural` — the offline gradient (the GenAI-free default, or the last-resort
 *                  fallback when every GenAI provider is unavailable)
 * - `reused`     — a brief-supplied input asset, reused as-is
 *
 * Surfaced on the asset and in the run log so the GenAI fallback chain is visible
 * (the pipeline degrades rather than failing a campaign).
 */
export type BackgroundSource = "firefly" | "imagen" | "openrouter" | "procedural" | "reused";
