/**
 * Where a creative's background came from:
 * - `imagen`     — generated by Google Imagen
 * - `procedural` — the offline gradient (the GenAI-free default, or the graceful
 *                  fallback when Imagen is unavailable / rate-limited)
 * - `reused`     — a brief-supplied input asset, reused as-is
 *
 * Surfaced on the asset and in the run log so the GenAI fallback is visible (the
 * pipeline degrades rather than failing a campaign).
 */
export type BackgroundSource = "imagen" | "procedural" | "reused";
